title: Techie Trooper
author: Amit Rai Sharma
email: me@techie-trooper.com
description: >- # this means to ignore newlines until "baseurl:"
  Learning And Sharing
github_username:  aarcosolutions
show_excerpts: true # set to false to remove excerpts on the homepage

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag