title: Techie Trooper
author: 
  name: Amit Rai Sharma
  email: me@techie-trooper.dev
description: >- # this means to ignore newlines until "baseurl:"
  Learning And Sharing
social_links:
    linkedin: amitraisharma
show_excerpts: true # set to false to remove excerpts on the homepage

# Build settings
theme: minima

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag