theme: jekyll-theme-hacker
title: Techie Trooper
author: Amit Rai Sharma
email: me@techie-trooper.com
description: >- # this means to ignore newlines until "baseurl:"
  Learning And Sharing
github_username:  aarcosolution

show_excerpts: true # set to false to remove excerpts on the homepage




